version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: academic_certificates
      POSTGRES_USER: ister
      POSTGRES_PASSWORD: 1ster
    ports:
      - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:
    driver: local